# Generated by Django 5.2.1 on 2025-05-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='individual', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='customer',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_pro.office', verbose_name='Office (for organizations)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='data_pro.client', verbose_name='Client Organization'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
