# Generated by Django 5.2.1 on 2025-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('CLIENT_ADMIN', 'Client Admin'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer')], max_length=20),
        ),
    ]
