# Generated by Django 5.2.1 on 2025-05-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_pro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='office',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='office',
        ),
    ]
